config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  
  resources :users do
    collection do
      get :account
      get :profile
    end
  end
  
  resources :hotels do
    collection do
      get :posts
      get :reservations
    end
  end
  
  resources :reservations do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  attachment :image
  
  def self.search(search,search1)
      @hotels = Hotel.where('address LIKE(?)', "%#{search}%").and(Hotel.where('name LIKE(?)', "%#{search1}%").or(Hotel.where('introduction LIKE(?)', "%#{search1}%")))
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :hotel, optional: true
    
    def keisan
        ((finish_day - start_day) / 1.days).to_i
    end
    
    def total_fee_price(hotel_price)
        use_day = keisan
        use_day * number_of_people * hotel_price
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :hotels, dependent: :destroy
  has_many :reservations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @user = current_user
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @user = current_user
    @hotels = Hotel.search(params[:area],params[:keyword])
  end
  
  def new
    @user = current_user
    @hotel = Hotel.new
  end
  
  def show
    @user = current_user
    @hotel = Hotel.find(params[:id])
    @reservation = Reservation.new
  end
  
  def create
    @hotel = Hotel.new(params.require(:hotel).permit(:name, :introduction, :price, :address, :image))
    @hotel.user_id = current_user.id
    @hotel.save
    redirect_to root_path
  end
  
  def posts
     @user = current_user
     @hotels = @user.hotels
  end
  
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @user = current_user
    @reservations = Reservation.all
    @hotels = Hotel.all
  end
  
  def new
    @user = current_user
    @reservation = Reservation.new
  end
  
  def confirm
    @user = current_user
    @reservation = Reservation.new(params.require(:reservation).permit(:start_day, :finish_day, :number_of_people, :days_of_use, :hotel_id))
    @hotel = Hotel.find(params[:reservation][:hotel_id])
  end
  
  def create
    @user = current_user
    @reservation = Reservation.new(params.require(:reservation).permit(:start_day, :finish_day, :number_of_people, :days_of_use, :total_fee, :user_id, :hotel_id))
    @hotel = Hotel.find(params[:reservation][:hotel_id])
    @reservation.save
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def update
    @user = current_user
    if @user.update(params.require(:user).permit(:profile_image, :username, :profile))
      flash[:notice] = "更新しました"
      redirect_to profile_users_path
    else
      render "edit"
    end
  end
  
  def account
    @user = current_user
  end
  
  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="top">
  <div class="top-main">
    <div class="container">
      <div class="row col-lg-6">
        <div class="form-fream">
          <div class="form-area">
            <p class="form-area-title">
              Potepan Shareでまだ体験したことのない旅をしよう
            </p>
            <%= form_with url: hotels_path, method: :get, local: true do |f| %>
              <%= f.label :area, "エリア" %>
              <%= f.search_field :area, class:"form-control mb-4" %>
              <%= f.submit "探す", class:"btn-primary mb-4" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="panel-area">
      <h1 class="section-title">
        おすすめのエリア
      </h1>
      <div class="row">
        <div class="panel-item col-6">
          <span>東京</span>
          <%= link_to hotels_path(area:'東京') do %>
            <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg", class:"panel-image" %>
          <% end %>
        </div>
        <div class="panel-item col-6">
          <span>大阪</span>
          <%= link_to hotels_path(area:'大阪') do %>
            <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg", class:"panel-image" %>
          <% end %>
        </div>
        <div class="panel-item col-6">
          <span>京都</span>
          <%= link_to hotels_path(area:'京都') do %>
            <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg", class:"panel-image" %>
          <% end %>
        </div>
        <div class="panel-item col-6">
          <span>札幌</span>
          <%= link_to hotels_path(area:'札幌') do %>
            <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg", class:"panel-image" %>
          <% end %>
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/hotels/index.html.erb
<div class="room">
  <h4 class="pb-4">検索結果：<%= @hotels.count %>件</h4>
  <div class="row">
    <% @hotels.each do |hotel| %>
      <div class="col-sm col-xl-3">
        <div class="room-frame-inner">
          <%= link_to hotel_path(hotel) do %>
            <div class="room-image-out">
              <%= attachment_image_tag hotel, :image, fallback: "no-image.png", class:"room-image" %>
            </div>
            <div class="room-profile">
              <p class="room-profile-name"><%= hotel.name %></p>
              <p class="room-profile-city"><%= hotel.address %></p>
              <p class="room-profile-price"><%= hotel.price %>円</p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hotels/new.html.erb
<div class="container-fiuld room-new">
  <div class="row">
    <div class="room-nav">
      <ul>
        <li class="active">
          <%= link_to "基本情報", "new_hotel_path" %>
        </li>
      </ul>
    </div>
    <div class="room-view col-lg-10">
      <div class="room-view-box">
        <%= form_with model:@hotel do |f| %>
          <div class="update-content">
            <div class="row">
              <h5>ルーム情報登録</h5>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :name, "ルーム名", class:"col-md" %>
              <%= f.text_field :name, class:"col-md form-control" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :introduction, "ルーム紹介", class:"col-md" %>
              <%= f.text_area :introduction, class:"col-md form-control" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :price, "料金", class:"col-md"%>
              <%= f.text_field :price, class:"col-md form-control" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :address, "住所", class:"col-md" %>
              <%= f.text_field :address, class:"col-md form-control" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :image, "ルーム画像", class:"col-md" %>
              <%= f.file_field :image, class:"col-md" %>
            </div>
          </div>
            <%= f.hidden_field :user_id, value:@user.id, class:"col-md" %>
          <div class="update-content">
            <div class="row">
              <%= f.submit "登録", class:"btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/hotels/posts.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>
    <tbody>
      <% @hotels.each do |hotel| %>
        <tr aling="center">
          <td><%= link_to (attachment_image_tag hotel, :image, fallback: "no-image.png", class: "room-posts-image"), hotel_path(hotel) %></td>
          <td class="posts-name"><%= link_to hotel.name, hotel_path(hotel) %></td>
          <td class="posts-content"><%= hotel.introduction %></td>
          <td class="price-icon"><%= hotel.price %></td>
          <td><%= hotel.created_at.to_s(:datetime_jp) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/hotels/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-md">
      <%= attachment_image_tag @hotel, :image, fallback: "no-image.png", class: "room-show-image" %>
      <div class="room-show-detile">
        <div class="room-show-detile-icon">
          <%= link_to (attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "host-icon"), "/" %>
        </div>
        <div class="room-show-profile">
          <p class="room-show-profile-name"><%= @hotel.name %></p>
          <p class="room-show-profile-address"><%= @hotel.address %></p>
        </div>
      </div>
      <p class="room-show-detile-content"><%= @hotel.introduction %></p>
    </div>
    <div class="col-md">
      <div class="room-show-nav">
        <h5 class="price-icon"><%= @hotel.price %>円/日</h5>
        <div class="room-show-date-select">
          <%= form_with model: @reservation, url: confirm_reservations_path do |f| %>
            <%= f.label :start_day, "開始日" %>
            <%= f.date_field :start_day, class:"form-control mb-4" %>
            <%= f.label :finish_day, "終了日" %>
            <%= f.date_field :finish_day, class:"form-control mb-4"  %>
            <%= f.label :number_of_people, "人数" %>
            <%= f.number_field :number_of_people, class:"form-control mb-4"  %>
            <%= f.hidden_field :hotel_id, :value => @hotel.id %>
            <%= f.submit "予約する", class:"btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-inner">
        <div class="header-left-nav">
          <%= link_to root_path do %>
            <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
          <% end %>
          <%= form_with url: hotels_path, method: :get, local: true do |f| %>
            <%= f.search_field :area, placeholder:"エリア検索", class:"form-control mb-4" %>
            <%= f.search_field :keyword, placeholder:"キーワード検索", class:"form-control mb-4" %>
            <%= f.submit "探す", style:"display:none" %>
          <% end %>
        </div>
        <div class="header-right-nav" id="header-right-nav-id">
          <% if user_signed_in? %>
            <div class="nav-item">
              <%= @user.username %>
            </div>
            <div class="nav-item" >
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "host-icon" %>
              <ul class="header-nav-menu display_n" id="header-nav-menu-id">
                <li>
                  <%= link_to "ルーム登録", new_hotel_path %>
                </li>
                <li>
                  <%= link_to "予約済みルーム一覧", reservations_path %>
                </li>
                <li>
                  <%= link_to "登録済みルーム一覧", posts_hotels_path %>
                </li>
                <li>
                  <%= link_to "設定", account_users_path %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか?"} %>
                </li>
              </ul>
            </div>
          <% else %>
            <%= link_to("ログイン", new_user_session_path, {class:"btn btn-primary"}) %>
            <%= link_to("登録する", new_user_registration_path, {class:"btn btn-secondary"}) %>
          <% end %>
        </div>
      </div>
    </header>
    
    <% if flash[:notice] %>
      <div class="notifications">
        <div class="notice">
          <%= notice %>
        </div>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div>
        <div>
          <%= alert %>
        </div>
      </div>
    <% end %>

    <%= yield %>
    
    <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
    <%= javascript_pack_tag 'users/usermenu.js' %>
  </body>
</html>

app/views/reservations/confirm.html.erb
<div class="container reservations-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservations-new-nav">
        <h4 class="reservations-new-check-content">予約内容確認</h4>
        <h5><%= @hotel.price %> 円/日</h5>
        <div class="reservations-new-date-select">
          <%= form_with model: @reservation do |f| %>
            <%= f.label :start_day, "□開始日" %>
            <%= f.date_field :start_day, :readonly => true, class:"form-control mb-4" %>
            <%= f.label :finish_day, "□終了日" %>
            <%= f.date_field :finish_day, :readonly => true, class:"form-control mb-4"  %>
            <h6 class="reservations-new-check-content"><%= "□使用日数：" + @reservation.keisan.to_s + "日" %></h6>
            <%= f.hidden_field :days_of_use, :value => @reservation.keisan.to_s %>
            <h6 class="reservations-new-check-content"><%= "□人数：" + @reservation.number_of_people.to_s + "人" %></h6>
            <%= f.hidden_field :number_of_people %>
            <%= f.label :total_fee, "合計金額" %>
            <%= f.number_field :total_fee, :value => @reservation.total_fee_price(@hotel.price) , :readonly => true, class:"form-control mb-4"  %>
            <%= f.hidden_field :user_id, :value => @user.id %>
            <%= f.hidden_field :hotel_id, :value => @hotel.id %>
            <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
            <%= f.submit "予約を確定", class:"btn btn-primary mb-4" %>
            <%= link_to "ルーム詳細に戻る", hotel_path(@hotel), {class:"form-control mb-4 btn"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/create.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-md-12 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">予約した部屋</label>
            <div class="col-md-9">
              <%= link_to @hotel.name, hotel_path(@hotel) %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">開始日</label>
            <div class="col-md-9">
              <%= @reservation.start_day.strftime('%Y年%m月%d日') %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">終了日</label>
            <div class="col-md-9">
              <%= @reservation.finish_day.strftime('%Y年%m月%d日') %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">価格</label>
            <div class="col-md-9">
              <%= @reservation.total_fee %>円
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>  
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <% @hotels.each do |hotel| %>
          <% if reservation.hotel_id == hotel.id %>
            <tr>
              <td>
                <%= link_to (attachment_image_tag hotel, :image, fallback: "no-image.png", class:"reservations-image"), hotel_path(hotel) %>
              </td>
              <td class="posts-name">
                <%= link_to hotel.name, hotel_path(hotel) %>
              </td>
              <td class="posts-content"><%= hotel.introduction %></td>
              <td class="price-icon"><%= reservation.total_fee%>円</td>
              <td><%= reservation.start_day.strftime('%Y-%m-%d')%></td>
              <td><%= reservation.finish_day.strftime('%Y-%m-%d')%></td>
              <td><%= reservation.created_at %></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_partial.html.erb
<div class="user-nav col-md">
  <ul>
    <li id="acount_id">
      <%= link_to "アカウント", account_users_path %>
    </li>
    <li id="profile_id">
     <%= link_to "プロフィール", profile_users_path %>
    </li>
  </ul>
</div>

app/views/users/account.html.erb
<div class="container-fiuld user">
  <div>
    <%= render "shared/partial" %>
    <div class="col-md user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>
              アカウント
            </h5>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md" for="email">
              メールアドレス
            </label>
            <div class="col-md">
              <%= @user.email%>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md" for="password">
              パスワード
            </label>
            <div class="col-md">
              *********
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <%= link_to("編集", edit_user_registration_path, {class:"btn btn-primary"}) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'users/account.js' %>

app/views/users/profile.html.erb
<div class="container-fiuld user">
  <div>
    <%= render "shared/partial" %>
    <div class="col-md user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>
              プロフィール
            </h5>
          </div>
        </div>
        <%= form_with model:@user, local:true do |f| %>
          <div class="update-content">
            <div class="row">
              <div class="col-6">
                <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png" %>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :profile_image, "アイコン画像", class:"col-md" %>
              <%= f.file_field :profile_image %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :username, "名前", class:"col-md" %>
              <%= f.text_field :username, class:"form-control" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :profile, "自己紹介", class:"col-md" %>
              <%= f.text_area :profile, class:"form-control" %>
            </div>
          </div>
          <div class="update-content">
            <div>
              <%= f.submit "更新", class:"btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'users/profile.js' %>